# Generated by Django 4.0.5 on 2023-07-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flow', models.CharField(max_length=100, verbose_name='客流量')),
                ('rate', models.CharField(max_length=100, verbose_name='准点率')),
                ('condition', models.CharField(max_length=100, verbose_name='车辆情况')),
                ('attendance', models.CharField(max_length=100, verbose_name='员工考勤')),
                ('emergency', models.CharField(max_length=100, verbose_name='紧急情况')),
                ('clear', models.CharField(max_length=100, verbose_name='环境整洁和设施维护')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('response', models.TextField(default='等待领导回复', verbose_name='领导回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'duties',
                'verbose_name_plural': 'duties',
                'db_table': 'duties',
            },
        ),
    ]
